export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const PERSIST_REHYDRATE = 'persist/REHYDRATE';

export const FETCH_USER_LOGGED_IN_SUCCESS = 'FETCH_USER_LOGGED_IN_SUCCESS';
export const FETCH_USER_LOGGED_IN_ERROR = 'FETCH_USER_LOGGED_IN_ERROR';
